apiVersion: batch/v1
kind: Job
metadata:
  name: pagerank
spec:
  template:
    spec:
      containers:
      - name: pagerank
        image: isabellyrocha/pagerank:raspberry-pi
        command: ["python", "/pagerank/pagerank.py", "--number-of-pages=10000", "--pages-file-name=/pagerank/pagerank.10k", "--iterations=3", "--start=0", "--end=9999", "--influx-host=10.96.21.32", "--influx-port=8086", "--influx-database=pagerank"]
      nodeSelector:
        kubernetes.io/hostname: vully-1
      restartPolicy: Never
  backoffLimit: 1
