apiVersion: batch/v1
kind: Job
metadata:
  name: pagerank-2-2
spec:
  template:
    spec:
      containers:
      - name: pagerank-2-2
        image: isabellyrocha/pagerank:raspberry-pi
        command: ["python", "/usr/local/bin/pagerank.py", "--number-of-pages=10000", "--pages-file-name=/usr/local/bin/pagerank.10k", "--iterations=3", "--start=5000", "--end=9999", "--influx-host=10.96.21.32", "--influx-port=8086", "--influx-database=pagerank"]
      nodeSelector:
        kubernetes.io/hostname: vully-2
      restartPolicy: Never
  backoffLimit: 1
